// COMPONENTS AND DATA IMPORT

/* HEADER START */
/* HEADER END */

/* HERO START */
/* HERO END */

/* FEATURES START */
import { Features } from './components/features/Features.js';
import { featuresData } from './data/featuresData.js';
/* FEATURES END */

/* COMMUNICATION START */
/* COMMUNICATION END */

/* DEVICE START */
/* DEVICE END */

/* HOW WORKS START */
/* HOW WORKS END */

/* GALLERY START */
/* GALLERY END */

/* TESTIMONIALS START */
/* TESTIMONIALS END */

/* PRICING START */
/* PRICING END */

/* FAQ START */
/* FAQ END */

/* TEAM START */
/* TEAM END */

/* APP STORE START */
/* APP STORE END */

/* SUBSCRIBE START */
/* SUBSCRIBE END */

/* CONTACT US START */
/* CONTACT US END */

/* FOOTER START */
/* FOOTER END */


// COMPONENTS EXECUTION

/* HEADER START */
/* HEADER END */

/* HERO START */
/* HERO END */

/* FEATURES START */
new Features('#features_block', featuresData);
/* FEATURES END */

/* COMMUNICATION START */
/* COMMUNICATION END */

/* DEVICE START */
/* DEVICE END */

/* HOW WORKS START */
/* HOW WORKS END */

/* GALLERY START */
/* GALLERY END */

/* TESTIMONIALS START */
/* TESTIMONIALS END */

/* PRICING START */
/* PRICING END */

/* FAQ START */
/* FAQ END */

/* TEAM START */
/* TEAM END */

/* APP STORE START */
/* APP STORE END */

/* SUBSCRIBE START */
/* SUBSCRIBE END */

/* CONTACT US START */
/* CONTACT US END */

/* FOOTER START */
/* FOOTER END */